source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

def app_pods
    pod 'SwiftyJSON'
    pod 'JSONWebToken'
    pod 'IQKeyboardManagerSwift'
    pod 'MBProgressHUD'
    pod 'Charts'
end

target 'ISPMIOT' do
    platform :ios, '9.0'
    app_pods
end
